version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - './site-data/db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3307:3306'
    networks:
      - wpsite
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '80:80'
    volumes: [
      "./site-data/wordpress:/var/www/html",
      "./kabelkrant_api:/var/www/html/wp-content/plugins/kabelkrant_api",
    ]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
      DEBUG_SITE: "kabelkrant"
    networks:
      - wpsite
networks:
  wpsite:

