name: App deploy

on:
  push:
    branches: 
      - main
      - staging
env:
  APP_FOLDER: obs-server/electron/kabelkrant-manager

jobs: 
  deploy-application:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Generate executable and deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm install
          npm run publish