name: Upload artifact
on: 
  push:
    branches: 
     - master
     - develop

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    #- name: Zip folder
    #  run: zip -r kabelkrant_api.zip ./plugin-wordpress/kabelkrant_api
    - name: Upload zip
      uses: actions/upload-artifact@v3.1.2
      with:
        name: kabelkrant-api
        path: ./plugin-wordpress/kabelkrant_api
      
